const CASES=window.CASE17_CASES||[];const state={filter:'الكل',solved:new Set(JSON.parse(localStorage.getItem('case17Solved')||'[]'))};
const homeView=document.getElementById('homeView'),caseView=document.getElementById('caseView'),caseGrid=document.getElementById('caseGrid'),caseContent=document.getElementById('caseContent');
const esc=s=>String(s??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[ch]));
const dc=d=>({'سهل':'easy','متوسط':'medium','صعب':'hard','خبير':'expert'})[d]||'';
const est=d=>({'سهل':'10–14','متوسط':'12–17','صعب':'15–21','خبير':'18–25'})[d]||'12–18';
function save(){localStorage.setItem('case17Solved',JSON.stringify([...state.solved]));updateProgress()}
function updateProgress(){const n=state.solved.size;document.getElementById('progressText').textContent=`${n} من ${CASES.length}`;document.getElementById('progressBar').style.width=`${n/CASES.length*100}%`}
function renderHome(){const list=state.filter==='الكل'?CASES:CASES.filter(c=>c.difficulty===state.filter);caseGrid.innerHTML=list.map(c=>`<button class="case-card ${state.solved.has(c.id)?'solved':''}" data-id="${c.id}"><div class="card-top"><span>القضية ${String(c.id).padStart(2,'0')}</span><span class="diff ${dc(c.difficulty)}">${esc(c.difficulty)}</span></div><h2>${esc(c.title)}</h2><p>${esc(c.place)} · ${esc(c.premise)}</p><div class="card-bottom"><span>فتح ملف التحقيق</span><span class="solved-tag">محلولة ✓</span></div></button>`).join('');caseGrid.querySelectorAll('.case-card').forEach(b=>b.onclick=()=>openCase(Number(b.dataset.id)));updateProgress()}
function openCase(id){const c=CASES.find(x=>x.id===id);if(!c)return;homeView.classList.add('hidden');caseView.classList.remove('hidden');window.scrollTo({top:0});caseContent.innerHTML=`<section class="case-head panel"><div class="case-top"><span>ملف ${String(c.id).padStart(2,'0')}</span><span class="diff ${dc(c.difficulty)}">${esc(c.difficulty)}</span></div><h1>${esc(c.title)}</h1><p>${esc(c.premise)}</p><div class="info-grid"><div class="info-box"><b>دورك</b>${esc(c.role)}</div><div class="info-box"><b>المكان</b>${esc(c.place)}</div><div class="info-box"><b>المهمة</b>${esc(c.mission)}</div></div></section><div class="case-stats"><span>🧩 ${c.evidence.length} دليل</span><span>👥 ${c.suspects.length} مشتبهين</span><span>⏱️ ${est(c.difficulty)} دقيقة</span></div><h3 class="section-title">ملفات المشتبهين</h3><div class="suspects">${c.suspects.map(s=>`<details class="suspect"><summary><span>👤 ${esc(s.name)}</span><small>${esc(s.role)}</small></summary><div>${esc(s.secret)}</div></details>`).join('')}</div><h3 class="section-title">الأدلة</h3><p class="hint">بعض الأدلة صحيحة لكنها مضللة في تفسيرها، وبعض الأشخاص يكذبون لسبب لا علاقة له بالجريمة.</p><div class="evidence-list">${c.evidence.map((ev,i)=>`<details class="evidence"><summary><span class="ecode">E-${String(i+1).padStart(2,'0')}</span><span>${esc(ev.title)}</span></summary><div>${esc(ev.text)}</div></details>`).join('')}</div><h3 class="section-title">توجيه الاتهام</h3><div class="accuse-list">${c.suspects.map((s,i)=>`<div class="accuse" data-index="${i}"><button>اتهام ${esc(s.name)}</button><div class="verdict"></div></div>`).join('')}</div><h3 class="section-title">دفتر المحقق</h3><textarea class="notes" placeholder="رتّب الزمن، فرّق بين إثبات الوجود وإثبات الهوية، ثم اختر المتهم."></textarea>`;caseContent.querySelectorAll('.accuse').forEach(row=>row.querySelector('button').onclick=()=>{const i=Number(row.dataset.index);caseContent.querySelectorAll('.accuse').forEach(x=>x.classList.remove('open','correct','wrong'));row.classList.add('open');const v=row.querySelector('.verdict');if(i===c.culprit){row.classList.add('correct');v.innerHTML=`<b>تم حل القضية.</b><br>${esc(c.solution)}`;state.solved.add(c.id);save()}else{row.classList.add('wrong');v.textContent='هذا الاتهام لا يفسر كل الأدلة. راجع التوقيت وطريقة التنفيذ والكذبة الجانبية.'}})}
document.getElementById('backBtn').onclick=()=>{caseView.classList.add('hidden');homeView.classList.remove('hidden');renderHome();window.scrollTo({top:0})};document.querySelectorAll('.filter').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.filter').forEach(b=>b.classList.remove('active'));btn.classList.add('active');state.filter=btn.dataset.filter;renderHome()});renderHome();